CODETOOLS-7903837: apidiff: build.sh issues on Windows
openjdk/apidiff pull request #12
Opened 2024-09-25 17:51 UTC by jonathan-gibbons

Please review some `build.sh` and `Makefile` changes to address issues building on Windows.

The primary Windows issue was missing use of `mixed_path` when passing some filenames into `make`.
There is some additional cleanup (for all platforms) to normalize the `DEPS_DIR` and add missing items to the `sanity` and `check_build_vars` targets.

This has been tested on macOS. Can someone with access to a Windows machine test it on Windows, please?

2024-09-25 19:17 UTC, sormuras commented
> This has been tested on macOS. Can someone with access to a Windows machine test it on Windows, please?

On it. An empty classpath element results in a `::` sequence, which seems to make MSYS2/Cygwin fail the build.

2024-09-25 19:21 UTC, sormuras approved these changes

2024-09-25 19:28 UTC, sormuras requested changes
https://github.com/openjdk/apidiff/blob/a10e1426e21978b522d93e1406731240197c2d37/test/junit/JUnitTests.gmk#L33 also needs some extra care to not pass an empty `$(DAISYDIFF_JAR)` element.

2024-09-25 19:48 UTC, sormuras approved these changes

2024-09-26 06:29 UTC, sormuras requested changes

2024-09-26 06:29 UTC, sormuras commented on test/junit/JUnitTests.gmk
> +		$(BUILDTESTDIR)/JUnitTests/classes:$(APIDIFF_IMAGEDIR)/lib/apidiff.jar:$(JAVADIFFUTILS_JAR):$(HTMLCLEANER_JAR)
```suggestion
		$(BUILDTESTDIR)/JUnitTests/classes:$(APIDIFF_IMAGEDIR)/lib/apidiff.jar:$(JAVADIFFUTILS_JAR):$(HTMLCLEANER_JAR):$(EQUINOX_JAR)
```

2024-10-01 18:22 UTC, irisclark approved these changes

2024-10-01 18:34 UTC, jonathan-gibbons commented
/integrate

2024-10-01 18:35 UTC, closed without merging